"""added temporary storage table

Revision ID: 14cc56a79317
Revises: e44fa2bf2db7
Create Date: 2026-08-19 08:46:08.674893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14cc56a79317'
down_revision: Union[str, Sequence[str], None] = 'e44fa2bf2db7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_signups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fullname', sa.String(length=30), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_signups_created_at'), 'pending_signups', ['created_at'], unique=False)
    op.create_index(op.f('ix_pending_signups_email'), 'pending_signups', ['email'], unique=True)
    op.create_index(op.f('ix_pending_signups_username'), 'pending_signups', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_signups_username'), table_name='pending_signups')
    op.drop_index(op.f('ix_pending_signups_email'), table_name='pending_signups')
    op.drop_index(op.f('ix_pending_signups_created_at'), table_name='pending_signups')
    op.drop_table('pending_signups')
    # ### end Alembic commands ###
