"""Initial migration

Revision ID: e44fa2bf2db7
Revises: 
Create Date: 2026-08-18 22:27:31.766092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e44fa2bf2db7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('fullname', sa.String(length=30), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_created_at'), 'accounts', ['created_at'], unique=False)
    op.create_index(op.f('ix_accounts_email'), 'accounts', ['email'], unique=True)
    op.create_index(op.f('ix_accounts_google_id'), 'accounts', ['google_id'], unique=True)
    op.create_index(op.f('ix_accounts_username'), 'accounts', ['username'], unique=True)
    op.create_table('email_otps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('otp_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_otps_email'), 'email_otps', ['email'], unique=False)
    op.create_index('ix_email_otps_email_created', 'email_otps', ['email', 'created_at'], unique=False)
    op.create_table('aqi_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('temperature_c', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('humidity_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('wind_speed_kmh', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('wind_direction_deg', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('pressure_hpa', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('solar_radiation_wm2', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('rainfall_mm', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('traffic_density_index', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('proximity_industrial_zone_km', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('month', sa.SmallInteger(), nullable=False),
    sa.Column('is_weekend', sa.Boolean(), nullable=False),
    sa.Column('prediction', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('day_of_week BETWEEN 0 AND 6', name='ck_history_day_of_week'),
    sa.CheckConstraint('humidity_pct BETWEEN 25 AND 100.0', name='ck_history_humidity'),
    sa.CheckConstraint('month BETWEEN 1 AND 12', name='ck_history_month'),
    sa.CheckConstraint('pressure_hpa BETWEEN 985 AND 1040', name='ck_history_pressure'),
    sa.CheckConstraint('proximity_industrial_zone_km BETWEEN 0.2 AND 20', name='ck_history_industrial_distance'),
    sa.CheckConstraint('rainfall_mm BETWEEN 0 AND 54.34', name='ck_history_rainfall'),
    sa.CheckConstraint('solar_radiation_wm2 BETWEEN 0 AND 793.5', name='ck_history_solar_radiation'),
    sa.CheckConstraint('temperature_c BETWEEN -7 AND 40', name='ck_history_temperature'),
    sa.CheckConstraint('traffic_density_index BETWEEN 0 AND 96.72', name='ck_history_traffic_density'),
    sa.CheckConstraint('wind_direction_deg BETWEEN 0 AND 360', name='ck_history_wind_direction'),
    sa.CheckConstraint('wind_speed_kmh BETWEEN 0.03 AND 54.33', name='ck_history_wind_speed'),
    sa.ForeignKeyConstraint(['user_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aqi_history_created_at'), 'aqi_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_aqi_history_user_id'), 'aqi_history', ['user_id'], unique=False)
    op.create_index('ix_history_user_created', 'aqi_history', ['user_id', 'created_at'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('uploaded_files',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('prediction_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('file_size > 0', name='ck_uploaded_file_size'),
    sa.CheckConstraint('prediction_count >= 0', name='ck_uploaded_file_prediction_count'),
    sa.CheckConstraint('row_count > 0', name='ck_uploaded_file_row_count'),
    sa.ForeignKeyConstraint(['user_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_uploaded_file_user_created', 'uploaded_files', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_uploaded_files_created_at'), 'uploaded_files', ['created_at'], unique=False)
    op.create_index(op.f('ix_uploaded_files_user_id'), 'uploaded_files', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uploaded_files_user_id'), table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_created_at'), table_name='uploaded_files')
    op.drop_index('ix_uploaded_file_user_created', table_name='uploaded_files')
    op.drop_table('uploaded_files')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_history_user_created', table_name='aqi_history')
    op.drop_index(op.f('ix_aqi_history_user_id'), table_name='aqi_history')
    op.drop_index(op.f('ix_aqi_history_created_at'), table_name='aqi_history')
    op.drop_table('aqi_history')
    op.drop_index('ix_email_otps_email_created', table_name='email_otps')
    op.drop_index(op.f('ix_email_otps_email'), table_name='email_otps')
    op.drop_table('email_otps')
    op.drop_index(op.f('ix_accounts_username'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_google_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_email'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_created_at'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
